name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
          DOCKER_USER: ${{secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    - name: Build  docker image
      run: |
        docker build -t juanpatron/docker-graphql:0.1.2  .
    - name: Push Docker image
      run: |
        docker push juanpatron/docker-graphql .
           
   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
